### ISSUE TITLE
Error when running ecs-cli compose --file docker-compose.yml up

### ISSUE THREAD

**Issue by ebuzz** [aws/amazon-ecs-cli#159]
Following the ECS CLI tutorial: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html

I am in the step number 3, when i try to execute `ecs-cli compose --file docker-compose.yml up` or `ecs-cli compose  up` with my docker-compose.yml file it throws this error.

panic: interface conversion: interface is string, not []interface {}
```
goroutine 1 [running]:
panic(0xb33c00, 0xc8201c9080)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config.readEnvFile(0x7f4d6020b130, 0x110c198, 0xc82015b280, 0x12, 0xc820159b60, 0x0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config/merge.go:89 +0x161
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config.parseV1(0x7f4d6020b130, 0x110c198, 0x7f4d6020b108, 0xc82015b6a0, 0xc82015b280, 0x12, 0xc820159b60, 0xc820159aa0, 0x10e56e0, 0xc820000180, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config/merge_v1.go:76 +0x79
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config.MergeServicesV1(0xc82015b6e0, 0x7f4d6020b108, 0xc82015b6a0, 0x7f4d6020b130, 0x110c198, 0xc82015b280, 0x12, 0xc820148c00, 0x1a3, 0x3a3, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config/merge_v1.go:40 +0x3c9
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config.Merge(0xc82015b6e0, 0x7f4d6020b108, 0xc82015b6a0, 0x7f4d6020b130, 0x110c198, 0xc82015b280, 0x12, 0xc820148c00, 0x1a3, 0x3a3, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config/merge.go:53 +0x5aa
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(*Project).load(0xc82015d930, 0xc82015b280, 0x12, 0xc820148c00, 0x1a3, 0x3a3, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:159 +0xdf
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc82015d930, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:84 +0x323
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*ecsProject).parseCompose(0xc82015d930, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:116 +0xfd
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*ecsProject).Parse(0xc82015d930, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:105 +0xde
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.projectFactory.loadProject(0x7f4d6020b248, 0xc82015d930, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/factory.go:101 +0x33
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.projectFactory.Create(0xc82016c1e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/factory.go:50 +0xe6
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.(*projectFactory).Create(0x110c198, 0xc82016c1e0, 0xc820139e00, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:2 +0xb8
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.WithProject.func1(0xc82016c1e0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/app.go:45 +0x6a
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xc38068, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdce340, 0xac, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:127 +0x1055
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc8200acd00, 0xc82016c000, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:257 +0xdac
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.startApp(0xc35238, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd53c20, 0x39, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:199 +0x74a
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xc35238, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd53c20, 0x39, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:55 +0x15f3
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200acb00, 0xc82000a050, 0x5, 0x5, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:159 +0xc34
main.main()
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:45 +0x9fa
```

Using version 1 syntax in my docker compose definition file:
web:
  image: [private ecs repository]
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  image: [private ecs repository]
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
Is there something that i am missing? 

Ran this command on different computers and it is the same result. Even the aws ecs-optimized amis but got the same result.

**Comment by kaihendry** [comment]
If I am reading that panic trace back, it's having issues reading your Env file back? Perhaps try set env like so https://docs.docker.com/compose/environment-variables/ ?

**Comment by ebuzz** [comment]
@kaihendry Don't know why is not reading it yet, i'll just remove it, thanks.
