### ISSUE TITLE
ecs-cli compose up error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by fernandoaleman** [aws/amazon-ecs-cli#193]
I am going through the [ecs-cli tutorial](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html) and upon trying to run `acs-cli compose up` I am getting the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x112cf0]

goroutine 1 [running]:
panic(0x8c0ae0, 0xc820010100)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(*Project).handleVolumeConfig(0xc8201d80f0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:319 +0x430
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(*Project).load(0xc8201d80f0, 0xc8201b77a0, 0x12, 0xc8201d2800, 0x499, 0x699, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:235 +0x649
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc8201d80f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:112 +0x335
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*ecsProject).parseCompose(0xc8201d80f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:116 +0xfd
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*ecsProject).Parse(0xc8201d80f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:105 +0xde
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.projectFactory.loadProject(0x134d3f0, 0xc8201d80f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/factory.go:101 +0x33
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.projectFactory.Create(0xc8200ab7c0, 0x12c600, 0x0, 0x0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/factory.go:50 +0xe6
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.(*projectFactory).Create(0x10a0650, 0xc8200ab7c0, 0x6b0d00, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:2 +0xb8
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.WithProject.func1(0xc8200ab7c0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/app.go:45 +0x6a
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.HandleAction(0x6bf480, 0xc8201ce450, 0xc8200ab7c0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:487 +0xe0
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xa36d38, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc52e80, 0xac, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:193 +0x104e
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc820116d00, 0xc8200ab540, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:374 +0x11e6
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.startApp(0xa33d48, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xba1c60, 0x39, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:280 +0xa39
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xa33d48, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xba1c60, 0x39, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:79 +0x7b
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).Run(0xc820116b60, 0xc82000a0f0, 0x5, 0x5, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:250 +0xc88
main.main()
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:45 +0xa79
```

I noticed that this issue was fixed in #105 but I seem to be getting the error again.

I am on `MacOS Sierra 10.12.2` using `ecs-cli 0.4.6`.

**Comment by Mihailoff** [comment]
Same on `ecs-cli version 0.4.6 (3e2a382)` `macOS SIerra 10.12.2`

**Comment by mrhein** [comment]
`ecs-cli version 0.4.6 (3e2a382` `MacOS Sierra 10.12.3 (16D32)` `go version go1.7.5 darwin/amd64`

same "feature"

**Comment by mrhein** [comment]
same on `0.4.6` `go 1.7` `osx 10.12.3`
```
ecs-cli compose --project-name escenic service create
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x1122f2]

goroutine 1 [running]:
panic(0x8c0ae0, 0xc82000e100)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(*Project).handleNetworkConfig(0xc8201ba0f0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:281 +0x282
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(*Project).load(0xc8201ba0f0, 0xc820197ce0, 0x12, 0xc8201c8000, 0x3ea, 0x5ea, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:234 +0x638
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc8201ba0f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:112 +0x335
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*ecsProject).parseCompose(0xc8201ba0f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:116 +0xfd
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(*ecsProject).Parse(0xc8201ba0f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:105 +0xde
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.projectFactory.loadProject(0x130d290, 0xc8201ba0f0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/factory.go:101 +0x33
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.projectFactory.Create(0xc82008d900, 0x12c601, 0x0, 0x0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/factory.go:50 +0xe6
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.(*projectFactory).Create(0x10a0650, 0xc82008d900, 0x6b0d01, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:2 +0xb8
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.WithProject.func1(0xc82008d900)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/app.go:45 +0x6a
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.HandleAction(0x6bf480, 0xc8201a8600, 0xc82008d900, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:487 +0xe0
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xa33df8, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc56180, 0x107, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:193 +0x104e
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc8200f3040, 0xc82008d680, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:374 +0x11e6
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.startApp(0xa364a0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbdc8c0, 0x50, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:280 +0xa39
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xa364a0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xbdc8c0, 0x50, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:79 +0x7b
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc8200f2ea0, 0xc82008d540, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:374 +0x11e6
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.startApp(0xa33d48, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xba1c60, 0x39, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:280 +0xa39
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xa33d48, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xba1c60, 0x39, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:79 +0x7b
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200f2d00, 0xc82000a0c0, 0x6, 0x6, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:250 +0xc88
main.main()
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:45 +0xa79
```

**Comment by anowell** [comment]
I hit this (in 0.4.6) when using a named volume in my compose file. Switching to absolute paths seemed to work around this for me - but certainly nothing in the docs helped me reach this conclusion.

**Comment by MichaelMackus** [comment]
Yup I'm getting the same error. See [this](https://github.com/aws/amazon-ecs-cli/issues/213#issuecomment-285193155) comment for full explanation & versions.

**Comment by yinshiua** [comment]
related to https://github.com/docker/libcompose/issues/430

**Comment by markzaretti** [comment]
I encountered this too running the following:
`ecs-cli compose --project-name xxxxxxx --file some-docker-compose-file.yml service up`

The solution was to edit the **docker-compose.yml** file.
NB. We were using docker-compose file version: '2'

**Changes made to resolve issue:**
1. avoid top level volumes: keyword and the use of named volumes.
2. Change volumes from:
    `- <volume name>:/absolute/path/in/container`
to
    `- /absolute/path/on/host:/absolute/path/in/container`

I hope this helps you.

**Comment by yinshiua** [comment]
@markzaretti Are you using the latest ecs-cli v0.5? This issue should have been fixed with https://github.com/docker/libcompose/pull/433
