### ISSUE TITLE
Random failures on cli commands

### ISSUE THREAD

**Issue by BenjaminCorey** [aws/amazon-ecs-cli#213]
The ecs-cli maybe works like 1 out of 10 times, the rest of the time it either hangs or I get random failures like this:

```
$ ecs-cli ps
zsh: segmentation fault  ecs-cli ps
```

```
$ ecs-cli ps
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x264d5bec0 pc=0x8e005]

goroutine 70 [running]:
runtime.throw(0xb811a0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8204a1600 sp=0xc8204a15e8
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8204a1650 sp=0xc8204a1600
runtime/internal/atomic.Load64(0x264d5bec0, 0x264d5bec6388d)
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0xc8204a1658 sp=0xc8204a1650
runtime.lfstackpop(0x1083328, 0x206f3)
	/usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0xc8204a1690 sp=0xc8204a1658
runtime.getempty(0x67, 0x0)
	/usr/local/go/src/runtime/mgcwork.go:341 +0x3b fp=0xc8204a16c0 sp=0xc8204a1690
runtime.(*gcWork).init(0xc82001b220)
	/usr/local/go/src/runtime/mgcwork.go:100 +0x53 fp=0xc8204a16d8 sp=0xc8204a16c0
runtime.(*gcWork).tryGet(0xc82001b220, 0x1)
	/usr/local/go/src/runtime/mgcwork.go:141 +0x38 fp=0xc8204a1708 sp=0xc8204a16d8
runtime.gcDrain(0xc82001b220, 0x5)
	/usr/local/go/src/runtime/mgcmark.go:833 +0x22a fp=0xc8204a1740 sp=0xc8204a1708
runtime.gcBgMarkWorker(0xc82001a000)
	/usr/local/go/src/runtime/mgc.go:1435 +0x583 fp=0xc8204a17b8 sp=0xc8204a1740
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8204a17c0 sp=0xc8204a17b8
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1330 +0x92

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc8200be000, 0xc8200c4460, 0x0, 0xc8201a70b0, 0x5, 0xc820155f60, 0x1f, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:714 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200be000, 0xc8200c4460, 0xc8200be000, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:314 +0x7e9
net/http.send(0xc8200c4460, 0x1308550, 0xc8200be000, 0x0, 0x0, 0x0, 0xc8201a7380, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0x1082d20, 0xc8200c4460, 0x0, 0x0, 0x0, 0x1135f, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0x1082d20, 0xc8200c4460, 0xc36b18, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0x1082d20, 0xc8200c4460, 0xaa0a8, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:191 +0x1e4
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/corehandlers.glob.func3(0xc8200f5880)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:103 +0x55
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc8200f5a08, 0xc8200f5880)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:136 +0xc3
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc8200f5880, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:374 +0x4d2
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs.(*ECS).DescribeClusters(0xc82002e138, 0xc820155b60, 0x1088318, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go:731 +0x4f
github.com/aws/amazon-ecs-cli/ecs-cli/modules/aws/clients/ecs.(*ecsClient).IsActiveCluster(0xc820155660, 0xc820135fc4, 0x3, 0xc820011020, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/aws/clients/ecs/client.go:476 +0x15f
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.validateCluster(0xc820135fc4, 0x3, 0x130ceb0, 0xc820155660, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:376 +0x65
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.clusterPS(0xc8200197c0, 0x130cf60, 0xc820135fe0, 0x130ceb0, 0xc820155660, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:364 +0x126
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.ClusterPS(0xc8200197c0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:108 +0x2ac
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.HandleAction(0x6bf480, 0xc36398, 0xc8200197c0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:487 +0xe0
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xa35cd0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb82820, 0x37, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:193 +0x104e
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200f2ea0, 0xc82000a280, 0x2, 0x2, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:250 +0xc88
main.main()
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:45 +0xa79

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
net/http.(*Transport).dialConn(0xc8200be000, 0x0, 0xc8201a70b0, 0x5, 0xc820155f60, 0x1f, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:837 +0x9c2
net/http.(*Transport).getConn.func4(0xc8200be000, 0x0, 0xc8201a70b0, 0x5, 0xc820155f60, 0x1f, 0xc820011500)
	/usr/local/go/src/net/http/transport.go:709 +0x66
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:711 +0x262

goroutine 17 [chan send]:
crypto/x509.execSecurityRoots(0xb58f5, 0x0, 0x0)
	/usr/local/go/src/crypto/x509/root_darwin.go:66 +0x4b5
crypto/x509.initSystemRoots()
	/usr/local/go/src/crypto/x509/root_nocgo_darwin.go:10 +0x18
sync.(*Once).Do(0x10a06c8, 0xc35e40)
	/usr/local/go/src/sync/once.go:44 +0xe4
crypto/x509.systemRootsPool(0x0)
	/usr/local/go/src/crypto/x509/root.go:15 +0x2f
crypto/x509.(*Certificate).Verify(0xc82023a000, 0xc820155f60, 0x1b, 0xc820214a50, 0x0, 0xed04bc19c, 0x2b27fdde, 0x1082e80, 0x0, 0x0, ...)
	/usr/local/go/src/crypto/x509/verify.go:241 +0x1de
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc82013de48, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:278 +0x6e9
crypto/tls.(*Conn).clientHandshake(0xc820226000, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:213 +0x1737
crypto/tls.(*Conn).Handshake(0xc820226000, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1033 +0xec
net/http.(*Transport).dialConn.func3(0xc820226000, 0xc82021e080, 0xc8202220c0)
	/usr/local/go/src/net/http/transport.go:831 +0x21
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:836 +0x986

goroutine 20 [runnable]:
syscall.readlen(0xf, 0xc8203eb8c0, 0x8, 0x6, 0xc8202ea000, 0x32)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1391
syscall.forkExec(0xacaeb0, 0x11, 0xc8202d0460, 0x5, 0x5, 0xc8203eba90, 0x138d3, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:202 +0x567
syscall.StartProcess(0xacaeb0, 0x11, 0xc8202d0460, 0x5, 0x5, 0xc8203eba90, 0x2, 0x4, 0x0, 0x0)
	/usr/local/go/src/syscall/exec_unix.go:240 +0x6b
os.startProcess(0xacaeb0, 0x11, 0xc8202d0460, 0x5, 0x5, 0xc8203ebcc8, 0xc82028ce00, 0x0, 0x0)
	/usr/local/go/src/os/exec_posix.go:45 +0x33e
os.StartProcess(0xacaeb0, 0x11, 0xc8202d0460, 0x5, 0x5, 0xc8203ebcc8, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:28 +0x69
os/exec.(*Cmd).Start(0xc820271040, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:332 +0x761
os/exec.(*Cmd).Run(0xc820271040, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:259 +0x2d
crypto/x509.verifyCertWithSystem(0xc8201ebb60, 0xc820246e80)
	/usr/local/go/src/crypto/x509/root_darwin.go:96 +0x714
crypto/x509.execSecurityRoots.func2(0xc820205930, 0xc820222480, 0xc820246e80)
	/usr/local/go/src/crypto/x509/root_darwin.go:53 +0x99
created by crypto/x509.execSecurityRoots
	/usr/local/go/src/crypto/x509/root_darwin.go:55 +0x355

goroutine 21 [running]:
	goroutine running on other thread; stack unavailable
created by crypto/x509.execSecurityRoots
	/usr/local/go/src/crypto/x509/root_darwin.go:55 +0x355

goroutine 22 [running]:
	goroutine running on other thread; stack unavailable
created by crypto/x509.execSecurityRoots
	/usr/local/go/src/crypto/x509/root_darwin.go:55 +0x355

goroutine 23 [runnable]:
runtime.SetFinalizer(0x9c9540, 0xc82019c6c0, 0x729fe0, 0xc36b40)
	/usr/local/go/src/runtime/mfinal.go:265
os.newProcess(0x138d2, 0x0, 0xc8202ca280)
	/usr/local/go/src/os/exec.go:22 +0x85
os.startProcess(0xacaeb0, 0x11, 0xc8202ca280, 0x5, 0x5, 0xc820477cc8, 0xc820282e00, 0x0, 0x0)
	/usr/local/go/src/os/exec_posix.go:49 +0x49e
os.StartProcess(0xacaeb0, 0x11, 0xc8202ca280, 0x5, 0x5, 0xc820477cc8, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/doc.go:28 +0x69
os/exec.(*Cmd).Start(0xc820147e00, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:332 +0x761
os/exec.(*Cmd).Run(0xc820147e00, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:259 +0x2d
crypto/x509.verifyCertWithSystem(0xc8201ebb00, 0xc820246e80)
	/usr/local/go/src/crypto/x509/root_darwin.go:96 +0x714
crypto/x509.execSecurityRoots.func2(0xc820205930, 0xc820222480, 0xc820246e80)
	/usr/local/go/src/crypto/x509/root_darwin.go:53 +0x99
created by crypto/x509.execSecurityRoots
	/usr/local/go/src/crypto/x509/root_darwin.go:55 +0x355
[signal 0xb code=0x1 addr=0x264d5bee0 pc=0x8e005]

runtime stack:
runtime/internal/atomic.Load64(0x264d5bee0, 0x264d5bee18de3)
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5
[signal 0xb code=0x1 addr=0x264d5bee0 pc=0x8e005]

runtime stack:
runtime/internal/atomic.Load64(0x264d5bee0, 0x264d5bee18de3)
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5
```

Any thoughts on what might be causing these?

**Comment by yinshiua** [comment]
might be related to https://github.com/aws/amazon-ecs-cli/issues/55

**Comment by yinshiua** [comment]
Hi, what versions of OS X, Go an ecs-cli are you using? If you can provide the detail of how you can reproduce this issue, I can better troubleshoot the issue.

**Comment by BenjaminCorey** [comment]
I'm on MacOS Sierra 10.12.3, ecs-cli version 0.4.6 (3e2a382)

**Comment by BenjaminCorey** [comment]
There might be multiple different issues here. I specified `aws_profile                 = default` in my `~/.ecs/config`, and the failures appear to happen less frequently. However, when executing commands that require I specific a keypair I still get errors 9 times out of 10.

For example:
```
$ ecs-cli up --keypair foo-key-pair-us-west-2 --capability-iam --size 2 --instance-type m3.medium
request expired, resigning
request expired, resigning
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x37c984]

goroutine 235 [running]:
runtime.throw(0xa344a0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820408880 sp=0xc820408868
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc8204088d0 sp=0xc820408880
net/http.(*Transport).dial(0xc8200d4000, 0xa36a20, 0x3, 0xc82027fb80, 0x1f, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:662 +0x94 fp=0xc820408960 sp=0xc8204088d0
net/http.(*Transport).dialConn(0xc8200d4000, 0x0, 0xc8204ac330, 0x5, 0xc82027fb80, 0x1f, 0x5293, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:765 +0x1e3d fp=0xc820408f00 sp=0xc820408960
net/http.(*Transport).getConn.func4(0xc8200d4000, 0x0, 0xc8204ac330, 0x5, 0xc82027fb80, 0x1f, 0xc8203b42a0)
	/usr/local/go/src/net/http/transport.go:709 +0x66 fp=0xc820408f78 sp=0xc820408f00
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820408f80 sp=0xc820408f78
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:711 +0x262

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc8200d4000, 0xc8203f47e0, 0x0, 0xc8204ac330, 0x5, 0xc82027fb80, 0x1f, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:714 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200d4000, 0xc8203f47e0, 0xc8200d4000, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:314 +0x7e9
net/http.send(0xc8203f47e0, 0x1308550, 0xc8200d4000, 0x0, 0x0, 0x0, 0xc8204acfc0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0x1082d20, 0xc8203f47e0, 0x0, 0x0, 0x0, 0x14, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0x1082d20, 0xc8203f47e0, 0xc36b18, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0x1082d20, 0xc8203f47e0, 0x43b5f3, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:191 +0x1e4
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/corehandlers.glob.func3(0xc820532000)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:103 +0x55
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc820532188, 0xc820532000)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:136 +0xc3
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc820532000, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:374 +0x4d2
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs.(*ECS).CreateCluster(0xc820030028, 0xc820030030, 0xc82054e1a8, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go:86 +0x4f
github.com/aws/amazon-ecs-cli/ecs-cli/modules/aws/clients/ecs.(*ecsClient).CreateCluster(0xc8201ad820, 0xc8201c8274, 0x3, 0x0, 0x0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/aws/clients/ecs/client.go:90 +0xe5
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.createCluster(0xc82001b7c0, 0x130d140, 0xc8201c82b0, 0x130d008, 0xc8201ad820, 0x130d0b8, 0xc8201bccf0, 0x130d118, 0xc820030108, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:239 +0x1417
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.ClusterUp(0xc82001b7c0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:64 +0x8d5
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.HandleAction(0x6bf480, 0xc363a8, 0xc82001b7c0, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:487 +0xe0
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xa36d38, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc411a0, 0x6c, 0x0, ...)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:193 +0x104e
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).Run(0xc82010cb60, 0xc82000a090, 0x9, 0x9, 0x0, 0x0)
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:250 +0xc88
main.main()
	/usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:45 +0xa79

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by BenjaminCorey** [comment]
Oh, not just instances where I specify I keypair. I'm also getting this:

```
$ ecs-cli compose --file docker-compose.ecs.yml service up
WARN[0000] Skipping unsupported YAML option...           option name=networks
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=api
WARN[0000] Skipping unsupported YAML option for service...  option name="depends_on" service name=frontend
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=frontend
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=worker
request expired, resigning
request expired, resigning
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0xe465b]
```

**Comment by yinshiua** [comment]
Can you also update what golang version you're using ? thanks!

**Comment by MichaelMackus** [comment]
I'm encountering the `panic: runtime error: invalid memory address or nil pointer dereference` error as well... currently unable to use ecs-cli at all :(.

```sh
$ uname -a
Linux michael-laptop 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
$ go version
go version go1.8 linux/amd64
$ ecs-cli -v
ecs-cli version 0.4.6 (3e2a382)

**Comment by BenjaminCorey** [comment]
```
$ go version
go version go1.8 darwin/amd64
```

**Comment by yinshiua** [comment]
@MichaelMackus can you provide the full stack trace of your error? Thanks!

**Comment by MichaelMackus** [comment]
@yinshiua actually, I think I fixed it but I can't recall exactly how... I think it had something to do with either docker-compose configuration or setting up the default cluster (which took me some time yesterday).

**Comment by yinshiua** [comment]
@MichaelMackus Can you update what command you're running so we know where to improve our validation? Thanks!

**Comment by yinshiua** [comment]
@BenjaminCorey Do you know if you have any existing docker containers running in your environment? From the investigation, we suspect that you may have docker containers running with too much constraint on memory and this was causing memory corruption.

Can you try cleaning up your environment by reinstalling Go1.8, delete `$GOPATH/pkg/*` contents, and reinstalling ecs-cli?

**Comment by MichaelMackus** [comment]
@yinshiua it was just `ecs-cli compose up --file FILENAME`. The problematic one was the `ecs-cli configure` command which isn't very great at validation IMO.

**Comment by yinshiua** [comment]
@MichaelMackus thank you for your feedback.

**Comment by BenjaminCorey** [comment]
@yinshiua this seems to have resolved itself on my machine, but I really can't say what I did...

Things it may have been:
1. Updated `~/.ecs/config` to contain `aws_profile = default`
2. Updated my docker-for-mac client
3. Deleting and recreating the cluster/instances/services

Thanks for looking into it

**Comment by yinshiua** [comment]
I am glad to hear that you are no longer seeing this issue. The containers that were running may have caused the memory corruption. Feel free to reopen this if the same error occur again.
