### ISSUE TITLE
1.4.0 "make test" fails

### ISSUE THREAD

**Issue by ilovezfs** [aws/amazon-ecs-cli#441]
### Summary
I'm trying to upgrade amazon-ecs-cli to 1.4.0 in Homebrew.

### Description
The build fails on the `make test` step.

### Expected Behavior
The build should not fail.

### Observed Behavior
```
=== RUN   TestConfigPermissions
--- PASS: TestConfigPermissions (0.00s)
=== RUN   TestPrefixesEmptyOldINIFormat
--- FAIL: TestPrefixesEmptyOldINIFormat (0.00s)
        Error Trace:    readwriter_v1_test.go:126
	Error:      	Received unexpected error:
	            	yaml: line 1: did not find expected <document start>
	            	Failed to parse yaml file: /tmp/ecs-cli-test-741917968/config
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.ReadClusterFile
	            		/private/tmp/amazon-ecs-cli-20180309-54793-1s9qpew/amazon-ecs-cli-1.4.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:88
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.readClusterConfig
	            		/private/tmp/amazon-ecs-cli-20180309-54793-1s9qpew/amazon-ecs-cli-1.4.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:111
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.(*YAMLReadWriter).Get
	            		/private/tmp/amazon-ecs-cli-20180309-54793-1s9qpew/amazon-ecs-cli-1.4.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:182
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.TestPrefixesEmptyOldINIFormat
	            		/private/tmp/amazon-ecs-cli-20180309-54793-1s9qpew/amazon-ecs-cli-1.4.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1_test.go:125
	            	testing.tRunner
	            		/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:777
	            	runtime.goexit
	            		/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361
	            	Error parsing /tmp/ecs-cli-test-741917968/config
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.(*YAMLReadWriter).Get
	            		/private/tmp/amazon-ecs-cli-20180309-54793-1s9qpew/amazon-ecs-cli-1.4.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:196
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.TestPrefixesEmptyOldINIFormat
	            		/private/tmp/amazon-ecs-cli-20180309-54793-1s9qpew/amazon-ecs-cli-1.4.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1_test.go:125
	            	testing.tRunner
	            		/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:777
	            	runtime.goexit
	            		/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361
	Messages:   	Error reading config
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x144575c]

goroutine 108 [running]:
testing.tRunner.func1(0xc4203ae870)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:742 +0x29d
panic(0x14c15c0, 0x1814750)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.TestPrefixesEmptyOldINIFormat(0xc4203ae870)
	/private/tmp/amazon-ecs-cli-20180309-54793-1s9qpew/amazon-ecs-cli-1.4.0/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1_test.go:127 +0x34c
testing.tRunner(0xc4203ae870, 0x1563840)
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.10/libexec/src/testing/testing.go:824 +0x2e0
FAIL	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config	0.341s
?   	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/ami	[no test files]
=== RUN   TestGetHomeDir
--- PASS: TestGetHomeDir (0.00s)
=== RUN   TestGetHomeDirInWindows
--- PASS: TestGetHomeDirInWindows (0.00s)
```
### Config files
n/a

Full log:
https://gist.github.com/ilovezfs/db8e0fbeae9285852bfd469e080d7c47

**Comment by samuelkarp** [comment]
`make test` passes with Go 1.9 and fails with Go 1.10 for me.

Here are the failures I see:

```
# github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/container
ecs-cli/modules/cli/compose/container/container_test.go:82: Errorf format %s has arg exitCode of wrong type int
# github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/license
ecs-cli/modules/cli/license/license_test.go:27: Errorf format %s has arg len(directories) of wrong type int
```

```
=== RUN   TestPopulateContextWithGlobalFlagOverrides
time="2018-03-12T19:33:28-07:00" level=error msg="Unable to create an instance of CLIParams given the cli context" error="Error loading config: Error parsing /tmp/test171421013/.ecs/config: Failed to parse yaml file: /tmp/test171421013/.ecs/config: yaml: line 1: did not find expected <document start>"
--- FAIL: TestPopulateContextWithGlobalFlagOverrides (0.00s)
        Error Trace:    factory_test.go:127
	Error:      	Received unexpected error:
	            	yaml: line 1: did not find expected <document start>
	            	Failed to parse yaml file: /tmp/test171421013/.ecs/config
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.ReadClusterFile
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:88
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.readClusterConfig
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:111
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.(*YAMLReadWriter).Get
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:182
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.NewCLIParams
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/params.go:60
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory.projectFactory.populateContext
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory/factory.go:78
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory.TestPopulateContextWithGlobalFlagOverrides
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory/factory_test.go:125
	            	testing.tRunner
	            		/home/skarp/.gobin/go/src/testing/testing.go:777
	            	runtime.goexit
	            		/home/skarp/.gobin/go/src/runtime/asm_amd64.s:2361
	            	Error parsing /tmp/test171421013/.ecs/config
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.(*YAMLReadWriter).Get
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:196
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.NewCLIParams
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/params.go:60
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory.projectFactory.populateContext
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory/factory.go:78
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory.TestPopulateContextWithGlobalFlagOverrides
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory/factory_test.go:125
	            	testing.tRunner
	            		/home/skarp/.gobin/go/src/testing/testing.go:777
	            	runtime.goexit
	            		/home/skarp/.gobin/go/src/runtime/asm_amd64.s:2361
	            	Error loading config
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.NewCLIParams
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/params.go:63
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory.projectFactory.populateContext
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory/factory.go:78
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory.TestPopulateContextWithGlobalFlagOverrides
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/compose/factory/factory_test.go:125
	            	testing.tRunner
	            		/home/skarp/.gobin/go/src/testing/testing.go:777
	            	runtime.goexit
	            		/home/skarp/.gobin/go/src/runtime/asm_amd64.s:2361
	Messages:   	Unexpected error
```

```
=== RUN   TestMigratePrefixesPresent
time="2018-03-12T19:33:17-07:00" level=info msg="Migrated ECS CLI configuration."
--- FAIL: TestMigratePrefixesPresent (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x822c62]

goroutine 32 [running]:
testing.tRunner.func1(0xc4201d8c30)
	/home/skarp/.gobin/go/src/testing/testing.go:742 +0x29d
panic(0x898ac0, 0xbd4850)
	/home/skarp/.gobin/go/src/runtime/panic.go:505 +0x229
github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/configure.TestMigratePrefixesPresent(0xc4201d8c30)
	/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/configure/configure_test.go:404 +0x632
testing.tRunner(0xc4201d8c30, 0x935048)
	/home/skarp/.gobin/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/skarp/.gobin/go/src/testing/testing.go:824 +0x2e0
FAIL	github.com/aws/amazon-ecs-cli/ecs-cli/modules/cli/configure	0.067s
```

```
# github.com/aws/amazon-ecs-cli/ecs-cli/modules/utils/compose
ecs-cli/modules/utils/compose/convert_task_definition_test.go:85: Errorf format %s has arg cpu of wrong type int64
ecs-cli/modules/utils/compose/convert_task_definition_test.go:103: Errorf format %s has arg memory of wrong type int64
ecs-cli/modules/utils/compose/convert_task_definition_test.go:109: Errorf format %s has arg privileged of wrong type bool
ecs-cli/modules/utils/compose/convert_task_definition_test.go:112: Errorf format %s has arg readOnly of wrong type bool
ecs-cli/modules/utils/compose/convert_task_definition_test.go:781: Errorf format %s has arg hostPort of wrong type int64
ecs-cli/modules/utils/compose/convert_task_definition_test.go:784: Errorf format %s has arg containerPort of wrong type int64
ecs-cli/modules/utils/compose/convert_task_definition_test.go:937: Errorf format %s has arg softLimit of wrong type int64
ecs-cli/modules/utils/compose/convert_task_definition_test.go:940: Errorf format %s has arg hardLimit of wrong type int64
ecs-cli/modules/utils/compose/convert_task_definition_test.go:1070: Errorf format %t has arg hasValues of wrong type map[string]bool
```

```
=== RUN   TestPrefixesEmptyOldINIFormat
--- FAIL: TestPrefixesEmptyOldINIFormat (0.00s)
        Error Trace:    readwriter_v1_test.go:126
	Error:      	Received unexpected error:
	            	yaml: line 1: did not find expected <document start>
	            	Failed to parse yaml file: /tmp/ecs-cli-test-936457953/config
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.ReadClusterFile
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:88
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.readClusterConfig
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:111
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.(*YAMLReadWriter).Get
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:182
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.TestPrefixesEmptyOldINIFormat
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1_test.go:125
	            	testing.tRunner
	            		/home/skarp/.gobin/go/src/testing/testing.go:777
	            	runtime.goexit
	            		/home/skarp/.gobin/go/src/runtime/asm_amd64.s:2361
	            	Error parsing /tmp/ecs-cli-test-936457953/config
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.(*YAMLReadWriter).Get
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1.go:196
	            	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.TestPrefixesEmptyOldINIFormat
	            		/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1_test.go:125
	            	testing.tRunner
	            		/home/skarp/.gobin/go/src/testing/testing.go:777
	            	runtime.goexit
	            		/home/skarp/.gobin/go/src/runtime/asm_amd64.s:2361
	Messages:   	Error reading config
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8442dc]

goroutine 152 [running]:
testing.tRunner.func1(0xc420305860)
	/home/skarp/.gobin/go/src/testing/testing.go:742 +0x29d
panic(0x8c07c0, 0xc107b0)
	/home/skarp/.gobin/go/src/runtime/panic.go:505 +0x229
github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.TestPrefixesEmptyOldINIFormat(0xc420305860)
	/home/skarp/go/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/readwriter_v1_test.go:127 +0x34c
testing.tRunner(0xc420305860, 0x9628e0)
	/home/skarp/.gobin/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/home/skarp/.gobin/go/src/testing/testing.go:824 +0x2e0
FAIL	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config	1.160s
?   	github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/ami	[no test files]
```

**Comment by SoManyHs** [comment]
Addressed by #445, pending release later this week.

**Comment by SoManyHs** [comment]
1.4.1 released. Closing.

**Comment by ilovezfs** [comment]
Thanks @SoManyHs!
