### ISSUE TITLE
"ecs-cli local up" TypeError: Object of type 'date' is not JSON serializable when date type used as environment

### ISSUE THREAD

**Issue by niroz89** [aws/amazon-ecs-cli#905]
### Summary

ecs-cli local up fails to start when there is environment variable value formatted as date. 
### Description

* Which specific command was run? `ecs-cli local up`
* Which version of the CLI you are using? `ecs-cli version 1.15.1 (628b3e6)`
* Which version of Go are you using? `go version go1.12.6 darwin/amd64`
* What platform are you using to run ECS CLI commands? MacOSX

#### task-defition.json
```
{
   "requiresCompatibilities":[
      "FARGATE"
   ],
   "containerDefinitions":[
      {
         "name":"nginx",
         "image":"nginx:latest",
         "memory":256,
         "cpu":256,
         "essential":true,
         "portMappings":[
            {
               "containerPort":80,
               "protocol":"tcp"
            }
         ],
         "environment":[
            {
               "name":"DATE",
               "value":"2019-07-22"
            }
         ],
         "logConfiguration":{
            "logDriver":"awslogs",
            "options":{
               "awslogs-group":"awslogs-nginx-ecs",
               "awslogs-region":"us-east-1",
               "awslogs-stream-prefix":"ecs"
            }
         }
      }
   ],
   "volumes":[

   ],
   "networkMode":"awsvpc",
   "placementConstraints":[

   ],
   "family":"nginx",
   "memory":"512",
   "cpu":"256"
}
```

### Expected Behavior
container should start
### Observed Behavior
``` 
#ecs-cli local up
INFO[0000] Task Definition network mode is ignored when running containers locally. Tasks will be run in the ecs-local-network.  networkMode=awsvpc
WARN[0000] awslogs log driver is ignored when running locally. Tasks will default to json-file instead. This can be changed in your compose override file.
INFO[0000] Successfully wrote docker-compose.ecs-local.yml
INFO[0000] Successfully wrote docker-compose.ecs-local.override.yml
INFO[0000] The network ecs-local-network already exists
INFO[0000] The amazon-ecs-local-container-endpoints container already exists with ID d172c41b1e3920fa5980c295af9e9c59638040495254dad8695c10eb58831fd6
INFO[0000] Started container with ID d172c41b1e3920fa5980c295af9e9c59638040495254dad8695c10eb58831fd6
INFO[0000] Using docker-compose.ecs-local.yml, docker-compose.ecs-local.override.yml files to start containers
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 42, in project_from_options
  File "compose/cli/command.py", line 115, in get_project
  File "compose/config/config.py", line 387, in load
  File "compose/config/config.py", line 387, in <listcomp>
  File "compose/config/config.py", line 554, in process_config_file
  File "compose/config/validation.py", line 452, in validate_against_config_schema
  File "compose/config/validation.py", line 513, in handle_errors
  File "compose/config/validation.py", line 513, in <genexpr>
  File "compose/config/validation.py", line 439, in process_config_schema_errors
  File "compose/config/validation.py", line 309, in handle_generic_error
  File "compose/config/validation.py", line 400, in _parse_oneof_validator
  File "json/__init__.py", line 231, in dumps
  File "json/encoder.py", line 199, in encode
  File "json/encoder.py", line 257, in iterencode
  File "json/encoder.py", line 180, in default
TypeError: Object of type 'date' is not JSON serializable
[66117] Failed to execute script docker-compose
FATA[0001] docker-compose up failed to exit successfully due to:
exit status 255
```
Generated docker-compose.ecs-local.yml
```
version: "3.4"
services:
  nginx:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      DATE: 2019-08-16
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: nginx:latest
    labels:
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: /tmp/task-definition.json
    logging:
      driver: awslogs
      options:
        awslogs-group: awslogs-nginx-ecs
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
    networks:
      ecs-local-network: null
    ports:
    - target: 80
      protocol: tcp
networks:
  ecs-local-network:
    external: true
```
I suppose when generating, if date format is forced as string, it will work.
```
 environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      DATE: "2019-08-16"
```

**Comment by efekarakus** [comment]
Hi @niroz89 ! I can re-create the issue, as you said it looks like if we wrap the value of the environment variable's value in quotes it fixes the issue. We'll work on a fix for this.

**Comment by efekarakus** [comment]
Fixed the issue in https://github.com/aws/amazon-ecs-cli/pull/908, pending release!
